### ISSUE TITLE
misuse of cv_iterator_traits

### ISSUE THREAD

**Issue by viboes** [vreverdy/bit#7]
Shouldn't it be `std::iterator_traits`in the next line?

https://github.com/vreverdy/bit/blob/67446ab8756f8bd5a670b92d9d75549959ba3de9/cpp/bit_iterator.hpp#L33

**Comment by vreverdy** [comment]
I don't think so. This is an implementation detail, only used to get the correctly cv-qualified word type (see the definition of word_type in bit_iterator). std::iterator_traits erases the cv-qualification of value_type. Does that answer the question?

**Comment by viboes** [comment]
Sorry, I misunderstood the intent.
